package is.hw.qdof.MAVServer;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeartbeatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 system_time = 1;
    /**
     * <code>required uint64 system_time = 1;</code>
     */
    boolean hasSystemTime();
    /**
     * <code>required uint64 system_time = 1;</code>
     */
    long getSystemTime();
  }
  /**
   * Protobuf type {@code Heartbeat}
   */
  public static final class Heartbeat extends
      com.google.protobuf.GeneratedMessage
      implements HeartbeatOrBuilder {
    // Use Heartbeat.newBuilder() to construct.
    private Heartbeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Heartbeat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Heartbeat defaultInstance;
    public static Heartbeat getDefaultInstance() {
      return defaultInstance;
    }

    public Heartbeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Heartbeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              systemTime_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Messages.internal_static_Heartbeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Messages.internal_static_Heartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Messages.Heartbeat.class, Messages.Heartbeat.Builder.class);
    }

    public static com.google.protobuf.Parser<Heartbeat> PARSER =
        new com.google.protobuf.AbstractParser<Heartbeat>() {
      public Heartbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Heartbeat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Heartbeat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 system_time = 1;
    public static final int SYSTEM_TIME_FIELD_NUMBER = 1;
    private long systemTime_;
    /**
     * <code>required uint64 system_time = 1;</code>
     */
    public boolean hasSystemTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 system_time = 1;</code>
     */
    public long getSystemTime() {
      return systemTime_;
    }

    private void initFields() {
      systemTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSystemTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, systemTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, systemTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Messages.Heartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Messages.Heartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Messages.Heartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Messages.Heartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Messages.Heartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Messages.Heartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Messages.Heartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Messages.Heartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Messages.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Messages.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Messages.Heartbeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Heartbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Messages.HeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Messages.internal_static_Heartbeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Messages.internal_static_Heartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Messages.Heartbeat.class, Messages.Heartbeat.Builder.class);
      }

      // Construct using Messages.Heartbeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        systemTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Messages.internal_static_Heartbeat_descriptor;
      }

      public Messages.Heartbeat getDefaultInstanceForType() {
        return Messages.Heartbeat.getDefaultInstance();
      }

      public Messages.Heartbeat build() {
        Messages.Heartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Messages.Heartbeat buildPartial() {
        Messages.Heartbeat result = new Messages.Heartbeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.systemTime_ = systemTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Messages.Heartbeat) {
          return mergeFrom((Messages.Heartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Messages.Heartbeat other) {
        if (other == Messages.Heartbeat.getDefaultInstance()) return this;
        if (other.hasSystemTime()) {
          setSystemTime(other.getSystemTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSystemTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Messages.Heartbeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Messages.Heartbeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 system_time = 1;
      private long systemTime_ ;
      /**
       * <code>required uint64 system_time = 1;</code>
       */
      public boolean hasSystemTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 system_time = 1;</code>
       */
      public long getSystemTime() {
        return systemTime_;
      }
      /**
       * <code>required uint64 system_time = 1;</code>
       */
      public Builder setSystemTime(long value) {
        bitField0_ |= 0x00000001;
        systemTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 system_time = 1;</code>
       */
      public Builder clearSystemTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        systemTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Heartbeat)
    }

    static {
      defaultInstance = new Heartbeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Heartbeat)
  }

  public interface AttitudeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required float roll = 1 [default = 0];
    /**
     * <code>required float roll = 1 [default = 0];</code>
     */
    boolean hasRoll();
    /**
     * <code>required float roll = 1 [default = 0];</code>
     */
    float getRoll();

    // required float pitch = 2 [default = 0];
    /**
     * <code>required float pitch = 2 [default = 0];</code>
     */
    boolean hasPitch();
    /**
     * <code>required float pitch = 2 [default = 0];</code>
     */
    float getPitch();

    // required float yaw = 3 [default = 0];
    /**
     * <code>required float yaw = 3 [default = 0];</code>
     */
    boolean hasYaw();
    /**
     * <code>required float yaw = 3 [default = 0];</code>
     */
    float getYaw();

    // required uint32 throttle = 4 [default = 0];
    /**
     * <code>required uint32 throttle = 4 [default = 0];</code>
     */
    boolean hasThrottle();
    /**
     * <code>required uint32 throttle = 4 [default = 0];</code>
     */
    int getThrottle();

    // optional float gx = 5 [default = 0];
    /**
     * <code>optional float gx = 5 [default = 0];</code>
     */
    boolean hasGx();
    /**
     * <code>optional float gx = 5 [default = 0];</code>
     */
    float getGx();

    // optional float gy = 6 [default = 0];
    /**
     * <code>optional float gy = 6 [default = 0];</code>
     */
    boolean hasGy();
    /**
     * <code>optional float gy = 6 [default = 0];</code>
     */
    float getGy();

    // optional float gz = 7 [default = 0];
    /**
     * <code>optional float gz = 7 [default = 0];</code>
     */
    boolean hasGz();
    /**
     * <code>optional float gz = 7 [default = 0];</code>
     */
    float getGz();

    // optional float temperature = 8 [default = 0];
    /**
     * <code>optional float temperature = 8 [default = 0];</code>
     */
    boolean hasTemperature();
    /**
     * <code>optional float temperature = 8 [default = 0];</code>
     */
    float getTemperature();
  }
  /**
   * Protobuf type {@code Attitude}
   */
  public static final class Attitude extends
      com.google.protobuf.GeneratedMessage
      implements AttitudeOrBuilder {
    // Use Attitude.newBuilder() to construct.
    private Attitude(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Attitude(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Attitude defaultInstance;
    public static Attitude getDefaultInstance() {
      return defaultInstance;
    }

    public Attitude getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Attitude(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              roll_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              pitch_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              yaw_ = input.readFloat();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              throttle_ = input.readUInt32();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              gx_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              gy_ = input.readFloat();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              gz_ = input.readFloat();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              temperature_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Messages.internal_static_Attitude_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Messages.internal_static_Attitude_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Messages.Attitude.class, Messages.Attitude.Builder.class);
    }

    public static com.google.protobuf.Parser<Attitude> PARSER =
        new com.google.protobuf.AbstractParser<Attitude>() {
      public Attitude parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Attitude(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Attitude> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required float roll = 1 [default = 0];
    public static final int ROLL_FIELD_NUMBER = 1;
    private float roll_;
    /**
     * <code>required float roll = 1 [default = 0];</code>
     */
    public boolean hasRoll() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float roll = 1 [default = 0];</code>
     */
    public float getRoll() {
      return roll_;
    }

    // required float pitch = 2 [default = 0];
    public static final int PITCH_FIELD_NUMBER = 2;
    private float pitch_;
    /**
     * <code>required float pitch = 2 [default = 0];</code>
     */
    public boolean hasPitch() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float pitch = 2 [default = 0];</code>
     */
    public float getPitch() {
      return pitch_;
    }

    // required float yaw = 3 [default = 0];
    public static final int YAW_FIELD_NUMBER = 3;
    private float yaw_;
    /**
     * <code>required float yaw = 3 [default = 0];</code>
     */
    public boolean hasYaw() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float yaw = 3 [default = 0];</code>
     */
    public float getYaw() {
      return yaw_;
    }

    // required uint32 throttle = 4 [default = 0];
    public static final int THROTTLE_FIELD_NUMBER = 4;
    private int throttle_;
    /**
     * <code>required uint32 throttle = 4 [default = 0];</code>
     */
    public boolean hasThrottle() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 throttle = 4 [default = 0];</code>
     */
    public int getThrottle() {
      return throttle_;
    }

    // optional float gx = 5 [default = 0];
    public static final int GX_FIELD_NUMBER = 5;
    private float gx_;
    /**
     * <code>optional float gx = 5 [default = 0];</code>
     */
    public boolean hasGx() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float gx = 5 [default = 0];</code>
     */
    public float getGx() {
      return gx_;
    }

    // optional float gy = 6 [default = 0];
    public static final int GY_FIELD_NUMBER = 6;
    private float gy_;
    /**
     * <code>optional float gy = 6 [default = 0];</code>
     */
    public boolean hasGy() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional float gy = 6 [default = 0];</code>
     */
    public float getGy() {
      return gy_;
    }

    // optional float gz = 7 [default = 0];
    public static final int GZ_FIELD_NUMBER = 7;
    private float gz_;
    /**
     * <code>optional float gz = 7 [default = 0];</code>
     */
    public boolean hasGz() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional float gz = 7 [default = 0];</code>
     */
    public float getGz() {
      return gz_;
    }

    // optional float temperature = 8 [default = 0];
    public static final int TEMPERATURE_FIELD_NUMBER = 8;
    private float temperature_;
    /**
     * <code>optional float temperature = 8 [default = 0];</code>
     */
    public boolean hasTemperature() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional float temperature = 8 [default = 0];</code>
     */
    public float getTemperature() {
      return temperature_;
    }

    private void initFields() {
      roll_ = 0F;
      pitch_ = 0F;
      yaw_ = 0F;
      throttle_ = 0;
      gx_ = 0F;
      gy_ = 0F;
      gz_ = 0F;
      temperature_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRoll()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPitch()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYaw()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasThrottle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, roll_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, pitch_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, yaw_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, throttle_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, gx_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, gy_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, gz_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(8, temperature_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, roll_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, pitch_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, yaw_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, throttle_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, gx_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, gy_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, gz_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, temperature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Messages.Attitude parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Messages.Attitude parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Messages.Attitude parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Messages.Attitude parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Messages.Attitude parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Messages.Attitude parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Messages.Attitude parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Messages.Attitude parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Messages.Attitude parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Messages.Attitude parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Messages.Attitude prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Attitude}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Messages.AttitudeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Messages.internal_static_Attitude_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Messages.internal_static_Attitude_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Messages.Attitude.class, Messages.Attitude.Builder.class);
      }

      // Construct using Messages.Attitude.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        roll_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        pitch_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        yaw_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        throttle_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        gx_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        gy_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        gz_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        temperature_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Messages.internal_static_Attitude_descriptor;
      }

      public Messages.Attitude getDefaultInstanceForType() {
        return Messages.Attitude.getDefaultInstance();
      }

      public Messages.Attitude build() {
        Messages.Attitude result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Messages.Attitude buildPartial() {
        Messages.Attitude result = new Messages.Attitude(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roll_ = roll_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pitch_ = pitch_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.yaw_ = yaw_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.throttle_ = throttle_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.gx_ = gx_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.gy_ = gy_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.gz_ = gz_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.temperature_ = temperature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Messages.Attitude) {
          return mergeFrom((Messages.Attitude)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Messages.Attitude other) {
        if (other == Messages.Attitude.getDefaultInstance()) return this;
        if (other.hasRoll()) {
          setRoll(other.getRoll());
        }
        if (other.hasPitch()) {
          setPitch(other.getPitch());
        }
        if (other.hasYaw()) {
          setYaw(other.getYaw());
        }
        if (other.hasThrottle()) {
          setThrottle(other.getThrottle());
        }
        if (other.hasGx()) {
          setGx(other.getGx());
        }
        if (other.hasGy()) {
          setGy(other.getGy());
        }
        if (other.hasGz()) {
          setGz(other.getGz());
        }
        if (other.hasTemperature()) {
          setTemperature(other.getTemperature());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoll()) {
          
          return false;
        }
        if (!hasPitch()) {
          
          return false;
        }
        if (!hasYaw()) {
          
          return false;
        }
        if (!hasThrottle()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Messages.Attitude parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Messages.Attitude) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required float roll = 1 [default = 0];
      private float roll_ ;
      /**
       * <code>required float roll = 1 [default = 0];</code>
       */
      public boolean hasRoll() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float roll = 1 [default = 0];</code>
       */
      public float getRoll() {
        return roll_;
      }
      /**
       * <code>required float roll = 1 [default = 0];</code>
       */
      public Builder setRoll(float value) {
        bitField0_ |= 0x00000001;
        roll_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float roll = 1 [default = 0];</code>
       */
      public Builder clearRoll() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roll_ = 0F;
        onChanged();
        return this;
      }

      // required float pitch = 2 [default = 0];
      private float pitch_ ;
      /**
       * <code>required float pitch = 2 [default = 0];</code>
       */
      public boolean hasPitch() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float pitch = 2 [default = 0];</code>
       */
      public float getPitch() {
        return pitch_;
      }
      /**
       * <code>required float pitch = 2 [default = 0];</code>
       */
      public Builder setPitch(float value) {
        bitField0_ |= 0x00000002;
        pitch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float pitch = 2 [default = 0];</code>
       */
      public Builder clearPitch() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pitch_ = 0F;
        onChanged();
        return this;
      }

      // required float yaw = 3 [default = 0];
      private float yaw_ ;
      /**
       * <code>required float yaw = 3 [default = 0];</code>
       */
      public boolean hasYaw() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float yaw = 3 [default = 0];</code>
       */
      public float getYaw() {
        return yaw_;
      }
      /**
       * <code>required float yaw = 3 [default = 0];</code>
       */
      public Builder setYaw(float value) {
        bitField0_ |= 0x00000004;
        yaw_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float yaw = 3 [default = 0];</code>
       */
      public Builder clearYaw() {
        bitField0_ = (bitField0_ & ~0x00000004);
        yaw_ = 0F;
        onChanged();
        return this;
      }

      // required uint32 throttle = 4 [default = 0];
      private int throttle_ ;
      /**
       * <code>required uint32 throttle = 4 [default = 0];</code>
       */
      public boolean hasThrottle() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 throttle = 4 [default = 0];</code>
       */
      public int getThrottle() {
        return throttle_;
      }
      /**
       * <code>required uint32 throttle = 4 [default = 0];</code>
       */
      public Builder setThrottle(int value) {
        bitField0_ |= 0x00000008;
        throttle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 throttle = 4 [default = 0];</code>
       */
      public Builder clearThrottle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        throttle_ = 0;
        onChanged();
        return this;
      }

      // optional float gx = 5 [default = 0];
      private float gx_ ;
      /**
       * <code>optional float gx = 5 [default = 0];</code>
       */
      public boolean hasGx() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float gx = 5 [default = 0];</code>
       */
      public float getGx() {
        return gx_;
      }
      /**
       * <code>optional float gx = 5 [default = 0];</code>
       */
      public Builder setGx(float value) {
        bitField0_ |= 0x00000010;
        gx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float gx = 5 [default = 0];</code>
       */
      public Builder clearGx() {
        bitField0_ = (bitField0_ & ~0x00000010);
        gx_ = 0F;
        onChanged();
        return this;
      }

      // optional float gy = 6 [default = 0];
      private float gy_ ;
      /**
       * <code>optional float gy = 6 [default = 0];</code>
       */
      public boolean hasGy() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional float gy = 6 [default = 0];</code>
       */
      public float getGy() {
        return gy_;
      }
      /**
       * <code>optional float gy = 6 [default = 0];</code>
       */
      public Builder setGy(float value) {
        bitField0_ |= 0x00000020;
        gy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float gy = 6 [default = 0];</code>
       */
      public Builder clearGy() {
        bitField0_ = (bitField0_ & ~0x00000020);
        gy_ = 0F;
        onChanged();
        return this;
      }

      // optional float gz = 7 [default = 0];
      private float gz_ ;
      /**
       * <code>optional float gz = 7 [default = 0];</code>
       */
      public boolean hasGz() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional float gz = 7 [default = 0];</code>
       */
      public float getGz() {
        return gz_;
      }
      /**
       * <code>optional float gz = 7 [default = 0];</code>
       */
      public Builder setGz(float value) {
        bitField0_ |= 0x00000040;
        gz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float gz = 7 [default = 0];</code>
       */
      public Builder clearGz() {
        bitField0_ = (bitField0_ & ~0x00000040);
        gz_ = 0F;
        onChanged();
        return this;
      }

      // optional float temperature = 8 [default = 0];
      private float temperature_ ;
      /**
       * <code>optional float temperature = 8 [default = 0];</code>
       */
      public boolean hasTemperature() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional float temperature = 8 [default = 0];</code>
       */
      public float getTemperature() {
        return temperature_;
      }
      /**
       * <code>optional float temperature = 8 [default = 0];</code>
       */
      public Builder setTemperature(float value) {
        bitField0_ |= 0x00000080;
        temperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float temperature = 8 [default = 0];</code>
       */
      public Builder clearTemperature() {
        bitField0_ = (bitField0_ & ~0x00000080);
        temperature_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Attitude)
    }

    static {
      defaultInstance = new Attitude(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Attitude)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Heartbeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Heartbeat_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Attitude_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Attitude_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\" \n\tHeartbeat\022\023\n\013system_" +
      "time\030\001 \002(\004\"\227\001\n\010Attitude\022\017\n\004roll\030\001 \002(\002:\0010" +
      "\022\020\n\005pitch\030\002 \002(\002:\0010\022\016\n\003yaw\030\003 \002(\002:\0010\022\023\n\010th" +
      "rottle\030\004 \002(\r:\0010\022\r\n\002gx\030\005 \001(\002:\0010\022\r\n\002gy\030\006 \001" +
      "(\002:\0010\022\r\n\002gz\030\007 \001(\002:\0010\022\026\n\013temperature\030\010 \001(" +
      "\002:\0010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Heartbeat_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Heartbeat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Heartbeat_descriptor,
              new java.lang.String[] { "SystemTime", });
          internal_static_Attitude_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Attitude_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Attitude_descriptor,
              new java.lang.String[] { "Roll", "Pitch", "Yaw", "Throttle", "Gx", "Gy", "Gz", "Temperature", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
