package is.hw.qdof.MAVServer;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeartbeatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 system_time = 1;
    boolean hasSystemTime();
    long getSystemTime();
  }
  public static final class Heartbeat extends
      com.google.protobuf.GeneratedMessage
      implements HeartbeatOrBuilder {
    // Use Heartbeat.newBuilder() to construct.
    private Heartbeat(Builder builder) {
      super(builder);
    }
    private Heartbeat(boolean noInit) {}
    
    private static final Heartbeat defaultInstance;
    public static Heartbeat getDefaultInstance() {
      return defaultInstance;
    }
    
    public Heartbeat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Messages.internal_static_Heartbeat_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Messages.internal_static_Heartbeat_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 system_time = 1;
    public static final int SYSTEM_TIME_FIELD_NUMBER = 1;
    private long systemTime_;
    public boolean hasSystemTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getSystemTime() {
      return systemTime_;
    }
    
    private void initFields() {
      systemTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSystemTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, systemTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, systemTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Messages.Heartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Messages.Heartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Messages.Heartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Messages.Heartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Messages.Heartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Messages.Heartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Messages.Heartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Messages.Heartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Messages.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Messages.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Messages.Heartbeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Messages.HeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Messages.internal_static_Heartbeat_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Messages.internal_static_Heartbeat_fieldAccessorTable;
      }
      
      // Construct using Messages.Heartbeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        systemTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Messages.Heartbeat.getDescriptor();
      }
      
      public Messages.Heartbeat getDefaultInstanceForType() {
        return Messages.Heartbeat.getDefaultInstance();
      }
      
      public Messages.Heartbeat build() {
        Messages.Heartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Messages.Heartbeat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Messages.Heartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Messages.Heartbeat buildPartial() {
        Messages.Heartbeat result = new Messages.Heartbeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.systemTime_ = systemTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Messages.Heartbeat) {
          return mergeFrom((Messages.Heartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Messages.Heartbeat other) {
        if (other == Messages.Heartbeat.getDefaultInstance()) return this;
        if (other.hasSystemTime()) {
          setSystemTime(other.getSystemTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSystemTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              systemTime_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 system_time = 1;
      private long systemTime_ ;
      public boolean hasSystemTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getSystemTime() {
        return systemTime_;
      }
      public Builder setSystemTime(long value) {
        bitField0_ |= 0x00000001;
        systemTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearSystemTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        systemTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Heartbeat)
    }
    
    static {
      defaultInstance = new Heartbeat(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Heartbeat)
  }
  
  public interface AttitudeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required float roll = 1 [default = 0];
    boolean hasRoll();
    float getRoll();
    
    // required float pitch = 2 [default = 0];
    boolean hasPitch();
    float getPitch();
    
    // required float yaw = 3 [default = 0];
    boolean hasYaw();
    float getYaw();
    
    // required uint32 throttle = 4 [default = 0];
    boolean hasThrottle();
    int getThrottle();
    
    // optional float gx = 5 [default = 0];
    boolean hasGx();
    float getGx();
    
    // optional float gy = 6 [default = 0];
    boolean hasGy();
    float getGy();
    
    // optional float gz = 7 [default = 0];
    boolean hasGz();
    float getGz();
    
    // optional float temperature = 8 [default = 0];
    boolean hasTemperature();
    float getTemperature();
    
    // required uint32 chk = 9 [default = 0];
    boolean hasChk();
    int getChk();
  }
  public static final class Attitude extends
      com.google.protobuf.GeneratedMessage
      implements AttitudeOrBuilder {
    // Use Attitude.newBuilder() to construct.
    private Attitude(Builder builder) {
      super(builder);
    }
    private Attitude(boolean noInit) {}
    
    private static final Attitude defaultInstance;
    public static Attitude getDefaultInstance() {
      return defaultInstance;
    }
    
    public Attitude getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Messages.internal_static_Attitude_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Messages.internal_static_Attitude_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required float roll = 1 [default = 0];
    public static final int ROLL_FIELD_NUMBER = 1;
    private float roll_;
    public boolean hasRoll() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public float getRoll() {
      return roll_;
    }
    
    // required float pitch = 2 [default = 0];
    public static final int PITCH_FIELD_NUMBER = 2;
    private float pitch_;
    public boolean hasPitch() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getPitch() {
      return pitch_;
    }
    
    // required float yaw = 3 [default = 0];
    public static final int YAW_FIELD_NUMBER = 3;
    private float yaw_;
    public boolean hasYaw() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getYaw() {
      return yaw_;
    }
    
    // required uint32 throttle = 4 [default = 0];
    public static final int THROTTLE_FIELD_NUMBER = 4;
    private int throttle_;
    public boolean hasThrottle() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getThrottle() {
      return throttle_;
    }
    
    // optional float gx = 5 [default = 0];
    public static final int GX_FIELD_NUMBER = 5;
    private float gx_;
    public boolean hasGx() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public float getGx() {
      return gx_;
    }
    
    // optional float gy = 6 [default = 0];
    public static final int GY_FIELD_NUMBER = 6;
    private float gy_;
    public boolean hasGy() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public float getGy() {
      return gy_;
    }
    
    // optional float gz = 7 [default = 0];
    public static final int GZ_FIELD_NUMBER = 7;
    private float gz_;
    public boolean hasGz() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public float getGz() {
      return gz_;
    }
    
    // optional float temperature = 8 [default = 0];
    public static final int TEMPERATURE_FIELD_NUMBER = 8;
    private float temperature_;
    public boolean hasTemperature() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public float getTemperature() {
      return temperature_;
    }
    
    // required uint32 chk = 9 [default = 0];
    public static final int CHK_FIELD_NUMBER = 9;
    private int chk_;
    public boolean hasChk() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getChk() {
      return chk_;
    }
    
    private void initFields() {
      roll_ = 0F;
      pitch_ = 0F;
      yaw_ = 0F;
      throttle_ = 0;
      gx_ = 0F;
      gy_ = 0F;
      gz_ = 0F;
      temperature_ = 0F;
      chk_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRoll()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPitch()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYaw()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasThrottle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChk()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, roll_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, pitch_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, yaw_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, throttle_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, gx_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, gy_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, gz_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(8, temperature_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt32(9, chk_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, roll_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, pitch_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, yaw_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, throttle_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, gx_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, gy_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, gz_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, temperature_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, chk_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Messages.Attitude parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Messages.Attitude parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Messages.Attitude parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Messages.Attitude parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Messages.Attitude parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Messages.Attitude parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Messages.Attitude parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Messages.Attitude parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Messages.Attitude parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Messages.Attitude parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Messages.Attitude prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Messages.AttitudeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Messages.internal_static_Attitude_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Messages.internal_static_Attitude_fieldAccessorTable;
      }
      
      // Construct using Messages.Attitude.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        roll_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        pitch_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        yaw_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        throttle_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        gx_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        gy_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        gz_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        temperature_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        chk_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Messages.Attitude.getDescriptor();
      }
      
      public Messages.Attitude getDefaultInstanceForType() {
        return Messages.Attitude.getDefaultInstance();
      }
      
      public Messages.Attitude build() {
        Messages.Attitude result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Messages.Attitude buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Messages.Attitude result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Messages.Attitude buildPartial() {
        Messages.Attitude result = new Messages.Attitude(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roll_ = roll_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pitch_ = pitch_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.yaw_ = yaw_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.throttle_ = throttle_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.gx_ = gx_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.gy_ = gy_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.gz_ = gz_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.temperature_ = temperature_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.chk_ = chk_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Messages.Attitude) {
          return mergeFrom((Messages.Attitude)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Messages.Attitude other) {
        if (other == Messages.Attitude.getDefaultInstance()) return this;
        if (other.hasRoll()) {
          setRoll(other.getRoll());
        }
        if (other.hasPitch()) {
          setPitch(other.getPitch());
        }
        if (other.hasYaw()) {
          setYaw(other.getYaw());
        }
        if (other.hasThrottle()) {
          setThrottle(other.getThrottle());
        }
        if (other.hasGx()) {
          setGx(other.getGx());
        }
        if (other.hasGy()) {
          setGy(other.getGy());
        }
        if (other.hasGz()) {
          setGz(other.getGz());
        }
        if (other.hasTemperature()) {
          setTemperature(other.getTemperature());
        }
        if (other.hasChk()) {
          setChk(other.getChk());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRoll()) {
          
          return false;
        }
        if (!hasPitch()) {
          
          return false;
        }
        if (!hasYaw()) {
          
          return false;
        }
        if (!hasThrottle()) {
          
          return false;
        }
        if (!hasChk()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              roll_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              pitch_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              yaw_ = input.readFloat();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              throttle_ = input.readUInt32();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              gx_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              gy_ = input.readFloat();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              gz_ = input.readFloat();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              temperature_ = input.readFloat();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              chk_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required float roll = 1 [default = 0];
      private float roll_ ;
      public boolean hasRoll() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public float getRoll() {
        return roll_;
      }
      public Builder setRoll(float value) {
        bitField0_ |= 0x00000001;
        roll_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoll() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roll_ = 0F;
        onChanged();
        return this;
      }
      
      // required float pitch = 2 [default = 0];
      private float pitch_ ;
      public boolean hasPitch() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getPitch() {
        return pitch_;
      }
      public Builder setPitch(float value) {
        bitField0_ |= 0x00000002;
        pitch_ = value;
        onChanged();
        return this;
      }
      public Builder clearPitch() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pitch_ = 0F;
        onChanged();
        return this;
      }
      
      // required float yaw = 3 [default = 0];
      private float yaw_ ;
      public boolean hasYaw() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getYaw() {
        return yaw_;
      }
      public Builder setYaw(float value) {
        bitField0_ |= 0x00000004;
        yaw_ = value;
        onChanged();
        return this;
      }
      public Builder clearYaw() {
        bitField0_ = (bitField0_ & ~0x00000004);
        yaw_ = 0F;
        onChanged();
        return this;
      }
      
      // required uint32 throttle = 4 [default = 0];
      private int throttle_ ;
      public boolean hasThrottle() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getThrottle() {
        return throttle_;
      }
      public Builder setThrottle(int value) {
        bitField0_ |= 0x00000008;
        throttle_ = value;
        onChanged();
        return this;
      }
      public Builder clearThrottle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        throttle_ = 0;
        onChanged();
        return this;
      }
      
      // optional float gx = 5 [default = 0];
      private float gx_ ;
      public boolean hasGx() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public float getGx() {
        return gx_;
      }
      public Builder setGx(float value) {
        bitField0_ |= 0x00000010;
        gx_ = value;
        onChanged();
        return this;
      }
      public Builder clearGx() {
        bitField0_ = (bitField0_ & ~0x00000010);
        gx_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float gy = 6 [default = 0];
      private float gy_ ;
      public boolean hasGy() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public float getGy() {
        return gy_;
      }
      public Builder setGy(float value) {
        bitField0_ |= 0x00000020;
        gy_ = value;
        onChanged();
        return this;
      }
      public Builder clearGy() {
        bitField0_ = (bitField0_ & ~0x00000020);
        gy_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float gz = 7 [default = 0];
      private float gz_ ;
      public boolean hasGz() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public float getGz() {
        return gz_;
      }
      public Builder setGz(float value) {
        bitField0_ |= 0x00000040;
        gz_ = value;
        onChanged();
        return this;
      }
      public Builder clearGz() {
        bitField0_ = (bitField0_ & ~0x00000040);
        gz_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float temperature = 8 [default = 0];
      private float temperature_ ;
      public boolean hasTemperature() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public float getTemperature() {
        return temperature_;
      }
      public Builder setTemperature(float value) {
        bitField0_ |= 0x00000080;
        temperature_ = value;
        onChanged();
        return this;
      }
      public Builder clearTemperature() {
        bitField0_ = (bitField0_ & ~0x00000080);
        temperature_ = 0F;
        onChanged();
        return this;
      }
      
      // required uint32 chk = 9 [default = 0];
      private int chk_ ;
      public boolean hasChk() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getChk() {
        return chk_;
      }
      public Builder setChk(int value) {
        bitField0_ |= 0x00000100;
        chk_ = value;
        onChanged();
        return this;
      }
      public Builder clearChk() {
        bitField0_ = (bitField0_ & ~0x00000100);
        chk_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Attitude)
    }
    
    static {
      defaultInstance = new Attitude(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Attitude)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Heartbeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Heartbeat_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Attitude_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Attitude_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\" \n\tHeartbeat\022\023\n\013system_" +
      "time\030\001 \002(\004\"\247\001\n\010Attitude\022\017\n\004roll\030\001 \002(\002:\0010" +
      "\022\020\n\005pitch\030\002 \002(\002:\0010\022\016\n\003yaw\030\003 \002(\002:\0010\022\023\n\010th" +
      "rottle\030\004 \002(\r:\0010\022\r\n\002gx\030\005 \001(\002:\0010\022\r\n\002gy\030\006 \001" +
      "(\002:\0010\022\r\n\002gz\030\007 \001(\002:\0010\022\026\n\013temperature\030\010 \001(" +
      "\002:\0010\022\016\n\003chk\030\t \002(\r:\0010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Heartbeat_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Heartbeat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Heartbeat_descriptor,
              new java.lang.String[] { "SystemTime", },
              Messages.Heartbeat.class,
              Messages.Heartbeat.Builder.class);
          internal_static_Attitude_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Attitude_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Attitude_descriptor,
              new java.lang.String[] { "Roll", "Pitch", "Yaw", "Throttle", "Gx", "Gy", "Gz", "Temperature", "Chk", },
              Messages.Attitude.class,
              Messages.Attitude.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
